spring:
  application:
    name: msworker
  datasource:
    url: jdbc:postgresql://db:5432/db_task
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

server:
  port: 0

logging:
  level:
    root: INFO
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","service":"${spring.application.name}","message":"%m"}%n'