services:
  mstask:
    build: .
    container_name: mstask
    depends_on:
      - db
    networks:
      - ms-network

  db:
    image: postgres:15-alpine
    container_name: postgres-mstask
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_task
    ports:
      - "5432:5432"
    volumes:
      - postgres_task_data:/var/lib/postgresql/data
    networks:
      - ms-network

networks:
  ms-network:
    external: true

volumes:
  postgres_task_data:
